<a href="https://colab.research.google.com/github/Shweta-sharma-1998/Task4/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### Assessment

###### I am going to provide two .csv files , you are supposed to work on them and have to provide solutions to the following problems

###### import necessary libraries

In [2]:
import pandas as pd
import numpy as np

###### merge those two csv files (after getting as dataframes, get them as a single dataframe)

In [4]:
file1= pd.read_csv("/content/college_1.csv")
file1

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0
3,Mugunthan S,100.0,47.0,10610,10610,Computer Science and Engineering,0
4,Sathammai.S,100.0,8.0,8980,8980,Computer Science and Engineering,0
...,...,...,...,...,...,...,...
79,KarthikeyanS,45.0,0.0,0,0,Electronics and Electrical Engineering,0
80,BARATH.P,29.0,0.0,0,0,Electronics and Electrical Engineering,0
81,N.Ajith kumar,82.0,0.0,0,0,Electronics and Electrical Engineering,0
82,mohamed nabi,0.0,0.0,0,0,Electronics and Electrical Engineering,0
83,yaser ahamed.A,0.0,27.0,0,0,Electronics and Electrical Engineering,0

In [5]:
file2= pd.read_csv("/content/college_2.csv")
file2

,Name,python,python_en,mysql,computational_thinking,Previous Geekions,CodeKata Score,Department,Rising
0,ASHOK KUMAR K,100,0,31,9,19400,19400,Electronics and Electrical Engineering,0
1,Chandru,0,20,0,0,14150,14490,Computer Science and Engineering,340
2,Ganesh Ramkumar R,-1,55,24,6,8790,10790,Computer Science and Engineering,2000
3,Bodipudi Harini,-1,0,35,-1,10040,10040,Electronics and Communication Engineering,0
4,VIINU V P,-1,100,24,-1,9150,9150,Electronics and Electrical Engineering,0
5,Poojitha Y,0,78,35,0,7210,8970,Computer Science and Engineering,1760
6,Gowtham Chandrasekaran,-1,0,0,3,7250,8950,Computer Science and Engineering,1700
7,Gowtham R,-1,60,4,6,8650,8650,Electronics and Communication Engineering,0
8,shifak N,58,0,0,0,5180,8320,Electronics and Electrical Engineering,3140
9,Balaji,-1,100,20,0,6170,8160,Electronics and Electrical Engineering,1990
10,Rushitha,-1,15,62,9,7470,8090,Computer Science and Engineering,620
11,Balaraman Muthupandi,-1,9,0,0,7670,8050,Computer Science and Engineering,380
12,JPradhap,100,0,0,0,7340,8030,Electronics and Electrical Engineering,690
13,SRIRAMKUMAR B,-1,0,0,0,6400,7940,Computer Science and Engineering,1540
14,Praneetha,-1,23,100,-1,7170,7730,Electronics and Communication Engineering,560
15,Rahul Raj K,-1,0,0,0,6280,7640,Computer Science and Engineering,1360
16,Guhan S,-1,72,35,39,7310,7630,Electronics and Communication Engineering,320
17,Suryarajan S,-1,63,31,0,6710,7550,Computer Science and Engineering,840
18,Narasimhan Y L,-1,-1,0,0,4800,6800,Computer Science and Engineering,2000
19,Leelakrishna,-1,6,4,0,5300,6640,Computer Science and Engineering,1340
20,PremsagarReddy,-1,20,0,0,5290,6290,Computer Science and Engineering,1000
21,pradeeban,16,20,24,0,6060,6090,Computer Science and Engineering,30
22,santhoshini,-1,43,0,0,3910,5740,Computer Science and Engineering,1830
23,MUKESH S M,-1,46,0,0,5200,5200,Computer Science and Engineering,0
24,P.GOVARDHANAN,-1,40,0,-1,5050,5050,Electronics and Communication Engineering,0
25,SHAIK DANISH,-1,43,0,0,4050,4820,Computer Science and Engineering,770
26,sridhar.s,-1,52,0,0,3860,4440,Computer Science and Engineering,580
27,Vimalesh Fernando,-1,0,0,0,4170,4170,Computer Science and Engineering,0
28,M.Karthikeyan,-1,0,4,6,4020,4020,Computer Science and Engineering,0
29,Abishak s,-1,55,35,6,3220,3220,Electronics and Communication Engineering,0
30,praveen raj j,24,-1,0,0,2380,2380,Computer Science and Engineering,0
31,AMARNATH D,-1,52,12,-1,1890,1890,Electronics and Communication Engineering,0
32,bala,32,49,0,-1,1720,1720,Electronics and Communication Engineering,0
33,XY Z,-1,20,-1,-1,0,0,Computer Science and Engineering,0
34,Hariharan,-1,-1,-1,0,0,0,Computer Science and Engineering,0

In [6]:
file1= "/content/college_1.csv"
file2= "/content/college_2.csv"
df = pd.concat(map(pd.read_csv, [file1, file2]), ignore_index=True)
df

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN
3,Mugunthan S,100.0,47.0,10610,10610,Computer Science and Engineering,0,NaN,NaN
4,Sathammai.S,100.0,8.0,8980,8980,Computer Science and Engineering,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
114,praveen raj j,24.0,0.0,2380,2380,Computer Science and Engineering,0,-1.0,0.0
115,AMARNATH D,-1.0,12.0,1890,1890,Electronics and Communication Engineering,0,52.0,-1.0
116,bala,32.0,0.0,1720,1720,Electronics and Communication Engineering,0,49.0,-1.0
117,XY Z,-1.0,-1.0,0,0,Computer Science and Engineering,0,20.0,-1.0
118,Hariharan,-1.0,-1.0,0,0,Computer Science and Engineering,0,-1.0,0.0

###### Take each csv file , split that csv file into multiple categories (example csv files are added in the repo)

###### consider if the codekata score exceeds 15000 points(present week) then make a csv on those observations as Exceeded expectations.csv

###### if  10000<codekata score<15000   (Reached_expectations.csv)

###### if  7000<codekata score<10000   (Needs_Improvement.csv)

###### if  codekate score < 7000        (Unsatisfactory.csv)

In [7]:
df2=df.loc[(df['CodeKata Score'] > 15000)]
df2.to_csv("Exceeded_Expectation.csv")
df3=df.loc[(df['CodeKata Score'] > 10000) & (df['CodeKata Score'] < 15000)]
df3.to_csv("Reached_Expectation.csv")
df4=df.loc[(df['CodeKata Score'] > 7000) & (df['CodeKata Score'] < 10000)]
df4.to_csv("Need_Improvement.csv")
df5=df.loc[(df['CodeKata Score'] < 7000)]
df5.to_csv("unsatisfactory.csv")

###### Average of previous week geekions vs this week geekions (i.e Previous Geekions vs CodeKata Score)

In [9]:
avg=df['Previous Geekions'].mean(axis=0)
avg1=df['CodeKata Score'].mean(axis=0)
print(avg)
print(avg1)

3842.3529411764707
4051.764705882353

###### No of students participated

In [10]:
print("Number of students participated:",df.Name.count())

Number of students participated: 119

###### #Average completion of python course or my_sql or python english or computational thinking

In [11]:
AVG=df.loc[(df['python']==100.0) | (df['mysql']==100.0) | (df['python_en']==100.0) | (df['computational_thinking']==100.0)]
print("Average completion of python course or my_sql or python english or computational thinking: ",(len(AVG.index)/len(df.index))*100)

Average completion of python course or my_sql or python english or computational thinking:  38.655462184873954

###### rising star of the week (top 3 candidate who performed well in that particular week)

In [12]:
df.nlargest(3,'Rising')

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
92,shifak N,58.0,0.0,5180,8320,Electronics and Electrical Engineering,3140,0.0,0.0
86,Ganesh Ramkumar R,-1.0,24.0,8790,10790,Computer Science and Engineering,2000,55.0,6.0
102,Narasimhan Y L,-1.0,0.0,4800,6800,Computer Science and Engineering,2000,-1.0,0.0

###### Shining stars of the week (top 3 candidates who has highest geekions)

In [13]:
df.nlargest(3,'CodeKata Score')

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN

###### Department wise codekata performence (pie chart)

In [14]:
import plotly.express as px
fig=px.pie(df,names='Department',values='CodeKata Score',title='Department wise codekata performence')
fig

###### Department wise toppers (horizantal bar graph or any visual representations of your choice)

In [16]:
Topper=px.scatter(df,x='Department',y='CodeKata Score',size='CodeKata Score',color='CodeKata Score',hover_data=['Name'],title='Department wise Topper')
Topper